#sudo yum install -y yum-utils
#sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
#sudo yum -y install vault

- name: Configuring hostname
  ansible.builtin.shell: set-hostname vault
#  ansible.builtin.shell: set-hostname {{ tool_name }}



- name: Configuring YUM repo of Hashicorp Vault
  ansible.builtin.shell: |
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    sudo yum -y install vault

- name: Installing Vault
  ansible.builtin.dnf:
    name: vault
    state: present

- name: Starting Vault
  ansible.builtin.systemd_service:
    name: vault
    state: restarted
    enabled: true
